### ISSUE TITLE
debug.* will be a no-op in next lualatex

### ISSUE THREAD

**Issue by kberry** [cochraef/LuaLaTeX-CAS#14]
Hi Evan - I noticed that luacas uses the debug.findupvalue and other debug.* Lua functions. 
I wanted to let you know that the 2024 Lua(La)TeX will make debug.* be nil by default, for security.

I hope there's another way you can accomplish what you're doing with the upvalues, without having to resort to --shell-escape? (At least I don't think luacas requires that now, which is great.)

Thanks,
Karl

**Comment by cochraef** [comment]
Thank you for the update Karl!

The debug functions are not called in LuaLaTeX from our style file. They are for debugging purposes and for people who want to run the CAS directly from Lua rather than using LuaLaTeX. 

From our testing, replacing all debug functions with null does not impact the function of the CAS when called from LaTeX.
